export const productsData = [
  {
    id: 1,
    title: "Soul",
    price: 19890,
    imageUrl: "./images/Soul.webp",
  },
  {
    id: 2,
    title: "Seltos",
    price: 23340,
    imageUrl: "./images/Seltos.webp",
  },
  {
    id: 3,
    title: "Sportage",
    price: 26290,
    imageUrl: "./images/Sportage.webp",
  },
  {
    id: 4,
    title: "Sorento",
    price: 30090,
    imageUrl: "./images/Sorento.webp",
  },
  {
    id: 5,
    title: "Carnival MPV",
    price: 33100,
    imageUrl: "./images/Carnival_MPV.webp",
  },
  {
    id: 6,
    title: "Telluride",
    price: 35890,
    imageUrl: "./images/Telluride.webp",
  },
  {
    id: 7,
    title: "Niro Hybrid",
    price: 26590,
    imageUrl: "./images/Niro_Hybrid.webp",
  },
  {
    id: 8,
    title: "Sportage Hybrid",
    price: 27490,
    imageUrl: "./images/Sportage_Hybrid.webp",
  },
  {
    id: 9,
    title: "Niro_Plug-in_Hybrid",
    price: 33840,
    imageUrl: "./images/Niro_Plug-in_Hybrid.webp",
  },
  {
    id: 10,
    title: "Sorento Hybrid",
    price: 36690,
    imageUrl: "./images/Sorento_Hybrid.webp",
  },
  {
    id: 11,
    title: "Sportage_Plug-in_Hybrid",
    price: 38690,
    imageUrl: "./images/Sportage_Plug-in_Hybrid.webp",
  },
  {
    id: 12,
    title: "Niro EV",
    price: 39550,
    imageUrl: "./images/Niro_EV.webp",
  },
  {
    id: 13,
    title: "EV6",
    price: 48700,
    imageUrl: "./images/EV6.webp",
  },
  {
    id: 14,
    title: "Sorento_Plug-in_Hybrid",
    price: 49990,
    imageUrl: "./images/Sorento_Plug-in_Hybrid.webp",
  },
  {
    id: 15,
    title: "Rio",
    price: 16750,
    imageUrl: "./images/Rio.webp",
  },
  {
    id: 16,
    title: "Rio 5-Door",
    price: 17690,
    imageUrl: "./images/Rio_5-Door.webp",
  },
  {
    id: 17,
    title: "Forte",
    price: 19690,
    imageUrl: "./images/Forte.webp",
  },
  {
    id: 18,
    title: "K5",
    price: 25290,
    imageUrl: "./images/K5.webp",
  },
  {
    id: 19,
    title: "Stinger",
    price: 36690,
    imageUrl: "./images/Stinger.webp",
  },
  {
    id: 20,
    title: "EV9",
    price: "Comming Soon",
    imageUrl: "./images/EV9.webp",
  },
  {
    id: 21,
    title: "2024 Seltos",
    price: "Comming Soon",
    imageUrl: "./images/2024_Seltos.webp",
  },
];
